apiVersion: v1
kind: Service
metadata:
  name: mcp-weather
  labels:
    app.kubernetes.io/name: mcp-weather
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mcp-weather    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-weather
  labels:
    app.kubernetes.io/name: mcp-weather    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-weather
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp-weather
        app.kubernetes.io/instance: release-name
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: mcp-weather
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          image: "quay.io/rh-aiservices-bu/mcp-weather:0.1.0-amd64"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: MCP_SERVER_HOST
              value: "0.0.0.0"
            - name: MCP_SERVER_PORT
              value: "3001"
            - name: WEATHER_CACHE_TTL
              value: "300"
            - name: WEATHER_API_KEY
              value: "demo-key"
            - name: WEATHER_PROVIDER
              value: "openweathermap"
            - name: WEATHER_DEMO_MODE
              value: "true"
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            tcpSocket:
              port: http
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            tcpSocket:
              port: http
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi