apiVersion: trustyai.opendatahub.io/v1alpha1
kind: EvalHub
metadata:
  name: evalhub
  namespace: evalhub
spec:
  tenancy: multi
  replicas: 1
  database:
    type: postgresql
    secret: evalhub-db-credentials  
  providers:
    - lm-evaluation-harness
    - garak
    - garak-kfp
    - guidellm
    - ibm-clear
  collections:
    - safety-and-fairness-v1
    - leaderboard-v2
    - toxicity-and-ethical-principles
    - model-validation
  env:
    - name: MLFLOW_TRACKING_URI
      value: "https://mlflow.redhat-ods-applications.svc:8443/mlflow"