apiVersion: kueue.openshift.io/v1
kind: Kueue
metadata:  
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-operator
  name: cluster    
spec:
  config:
    integrations:
      frameworks:
        - BatchJob
        - StatefulSet
        - Pod
    preemption:
      preemptionPolicy: Classical
  logLevel: Normal
  managementState: Managed
  operatorLogLevel: Normal