apiVersion: v1
kind: Namespace
metadata:    
  name: mcp-gateway
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mcp-gateway
  namespace: mcp-gateway
spec:
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: mcp-gateway
  channel: preview
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: mcp-gateway
  namespace: mcp-gateway
spec:
  targetNamespaces:
  - mcp-gateway