apiVersion: mlflow.opendatahub.io/v1
kind: MLflow
metadata:
  name: mlflow
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: managed-nfs-storage  
  backendStoreUriFrom: 
    name: mlflow-db-credentials 
    key: backend-store-uri
  artifactsDestination: "file:///mlflow/artifacts"
  serveArtifacts: true