apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ClusterPolicy.v1.nvidia.com
  name: nvidia-gpu-operator
  namespace: nvidia-gpu-operator
spec:
  targetNamespaces:
  - nvidia-gpu-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gpu-operator-certified.nvidia-gpu-operator: ""
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gpu-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
# ---
# kind: ClusterPolicy
# apiVersion: nvidia.com/v1
# metadata:
#   name: gpu-cluster-policy
# spec:
#   operator:
#     defaultRuntime: crio
#     use_ocp_driver_toolkit: true
#     initContainer: {}
#   sandboxWorkloads:
#     enabled: false
#     defaultWorkload: container
#   driver:
#     enabled: true
#     upgradePolicy:
#       autoUpgrade: true
#       drain:
#         deleteEmptyDir: false
#         enable: false
#         force: false
#         timeoutSeconds: 300
#       maxParallelUpgrades: 1
#       maxUnavailable: 25%
#       podDeletion:
#         deleteEmptyDir: false
#         force: false
#         timeoutSeconds: 300
#       waitForCompletion:
#         timeoutSeconds: 0
#     repoConfig:
#       configMapName: ''
#     certConfig:
#       name: ''
#     licensingConfig:
#       nlsEnabled: false
#       configMapName: ''
#     virtualTopology:
#       config: ''
#     kernelModuleConfig:
#       name: ''
#   dcgmExporter:
#     enabled: true
#     config:
#       name: ''
#     serviceMonitor:
#       enabled: true
#   dcgm:
#     enabled: true
#   daemonsets:
#     updateStrategy: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: '1'
#   devicePlugin:
#     enabled: true
#     config:
#       name: ''
#       default: ''
#   gfd:
#     enabled: true
#   migManager:
#     enabled: true
#   nodeStatusExporter:
#     enabled: true
#   mig:
#     strategy: single
#   toolkit:
#     enabled: true
#   validator:
#     plugin:
#       env:
#         - name: WITH_WORKLOAD
#           value: 'false'
#   vgpuManager:
#     enabled: false
#   vgpuDeviceManager:
#     enabled: true
#   sandboxDevicePlugin:
#     enabled: true
#   vfioManager:
#     enabled: true
#   gds:
#     enabled: false