FROM registry.redhat.io/ubi9/python-312:latest

RUN pip install --upgrade pip
RUN pip install --upgrade huggingface_hub

# Set working directory
WORKDIR /tmp

RUN curl -L -o openshift-client.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.19/openshift-client-linux.tar.gz && \
    tar -xzf openshift-client.tar.gz && \
    cp oc kubectl /opt/app-root/bin/ && \
    chmod 755 /opt/app-root/bin/oc /opt/app-root/bin/kubectl

RUN curl -L -o /opt/app-root/bin/jq \
    https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64 && \
    chmod 755 /opt/app-root/bin/jq
    
RUN curl -L -o /opt/app-root/bin/mc \
    https://dl.min.io/client/mc/release/linux-amd64/mc && \
    chmod 755 /opt/app-root/bin/mc

USER root
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    mkdir -p /opt/aws-cli && \
    ./aws/install -i /opt/aws-cli -b /opt/app-root/bin
RUN dnf -y install hostname bind-utils nmap-ncat

RUN dnf clean all
RUN rm -rf /tmp/*

USER 1001
WORKDIR /opt/app-root/src
COPY sync-models.sh bin/sync-models.sh