kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-creator: 'kube:admin'
    opendatahub.io/notebook-image-desc: ''
    opendatahub.io/notebook-image-name: LLM Compressor'
    opendatahub.io/notebook-image-url: 'quay.io/opendatahub/llmcompressor-workbench:main'
    opendatahub.io/recommended-accelerators: '[]'
    openshift.io/image.dockerRepositoryCheck: '2025-09-12T06:21:59Z'  
  name: llmcompressor
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: main
      annotations:
        opendatahub.io/notebook-python-dependencies: '[]'
        opendatahub.io/notebook-software: '[]'
        openshift.io/imported-from: 'quay.io/opendatahub/llmcompressor-workbench:main'
      from:
        kind: DockerImage
        name: 'quay.io/opendatahub/llmcompressor-workbench:main'
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source