apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem